// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/tikhomirovv/lazy-investor/internal/adapters/marketdata/tinkoff"
	"github.com/tikhomirovv/lazy-investor/internal/adapters/report/chart"
	"github.com/tikhomirovv/lazy-investor/internal/adapters/telegram"
	"github.com/tikhomirovv/lazy-investor/internal/application"
	"github.com/tikhomirovv/lazy-investor/pkg/config"
	"github.com/tikhomirovv/lazy-investor/pkg/logging"
	"os"
)

// Injectors from wire.go:

// InitConfig returns config from YAML file.
func InitConfig() (*config.Config, error) {
	string2 := providerConfigPath()
	configConfig, err := config.NewConfig(string2)
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}

// InitLogger returns the default zerolog-based logger.
func InitLogger() *logging.ZLogger {
	zLogger := logging.NewLogger()
	return zLogger
}

// InitTinkoffService builds Tinkoff market data adapter.
func InitTinkoffService(logger logging.Logger) (*tinkoff.Service, error) {
	tinkoffConfig := providerTinkoffConfig()
	service, err := tinkoff.NewService(tinkoffConfig, logger)
	if err != nil {
		return nil, err
	}
	return service, nil
}

// InitApplication builds the main application with all adapters (market data, chart, telegram).
func InitApplication() (*application.Application, error) {
	string2 := providerConfigPath()
	configConfig, err := config.NewConfig(string2)
	if err != nil {
		return nil, err
	}
	zLogger := logging.NewLogger()
	tinkoffConfig := providerTinkoffConfig()
	service, err := tinkoff.NewService(tinkoffConfig, zLogger)
	if err != nil {
		return nil, err
	}
	chartService := chart.NewService()
	telegramConfig := providerTelegramConfig()
	telegramService := telegram.NewService(telegramConfig, zLogger)
	applicationApplication := application.NewApplication(configConfig, zLogger, service, chartService, telegramService)
	return applicationApplication, nil
}

// wire.go:

const configPath = "./config.yml"

func providerConfigPath() string {
	return configPath
}

func providerTinkoffConfig() tinkoff.Config {
	return tinkoff.Config{
		AppName: os.Getenv("APP_NAME"),
		Host:    os.Getenv("TINKOFF_API_HOST"),
		Token:   os.Getenv("TINKOFF_API_TOKEN"),
	}
}

// providerTelegramConfig returns Telegram adapter config from env. Empty token/chatID = no-op mode.
func providerTelegramConfig() telegram.Config {
	return telegram.Config{
		Token:  os.Getenv("TELEGRAM_BOT_TOKEN"),
		ChatID: os.Getenv("TELEGRAM_CHAT_ID"),
	}
}
